modLoader="javafml"
loaderVersion="[38,)"
license="MIT License"
issueTrackerURL="${mod_issues}"
showAsResourcePack=false

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_homepage}"
logoFile="logo.png"
authors="${mod_author}"
description="${mod_description}"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[1.19,)"
ordering="NONE"
side="CLIENT"
